### ISSUE TITLE
Date is not correctly displayed Inside bootstrap modal

### ISSUE THREAD

**Issue by affiliatepayday** [mtrdesign/mtr-datepicker#27]
If I load this inside a bootstrap modal that is initially set to display none - the date displays wrong, but still seems to be set correctly. 

When I launch the modal it will show the date as Jan 1, Wed 1, 2020. 

When clicking to change date information however it is based off todays date: so for example if I change the month, it will currently change from Jan to either July or May (as the current month is june). If I change the date it will change to the 26th or the 28th, as the date is the 27th. 

So it seems the date IS correct, but its is SHOWING incorrect. 

See bug https://jsfiddle.net/3kxzfoLr/

**Comment by affiliatepayday** [comment]
Got it sorted but still think it would be better if it didn't need wrapped in a modal function. 

```
  $('#modal-name').on('shown.bs.modal', function (e) {
     datepickerDefault = new MtrDatepicker({
       target: "demo",
       timepicker: false,
     });
  });
```

**Comment by valkirilov** [comment]
Hi @affiliatepayday, I'm glad you found a way to solve the issue for your case.

Also I managed to address the bug - it's caused by the fact the datepicker is not visible during the initialization so the offset of the values can't be calculated properly and when you open the modal it leads you to see the first value of every field (hour, minute, date, month, year). 

Unfortunately I read the webkit specification and its desired behavior tfor the `offsetTop` property to be always zero when elements are not visible. I agree that such behavior of the datepicker is confusing and a bit buggy, but right now I'm not sure how to fix it. I'll keep that in my mind and will try to find a solution.
