### ISSUE TITLE
disable PM / AM

### ISSUE THREAD

**Issue by NadirBertolasi** [mtrdesign/mtr-datepicker#6]
Hi,
is there a way to disable PM / AM switch and use a full 24 hour format?

Thank you

**Comment by valkirilov** [comment]
Hi @NadirBertolasi,

Unfortunately this feature is not available  for now. Thank you.

**Comment by NadirBertolasi** [comment]
Thank you for the answer

**Comment by valkirilov** [comment]
Hi @NadirBertolasi,

good news for you, the datepicker now supports a full 24 hours time format!
In order to use it you should download the latest update of the lib and then use the `disableAmPm` param during the initialization process. Here is a brief example:

```
<div id="disable-ampm-mtr-datepicker"></div>

<script>
  var config = {
    target: 'disable-ampm-mtr-datepicker',
    disableAmPm: true
  };
  var myDatepicker = new MtrDatepicker(config);
</script>
```

I hope that you'll like the new update and continue to use MTR Datepicker in your current and future projects, thanks you! :)
